- hosts: clients
  become: true
  tasks:
    - name: "Creating vectorspace user"
      when: ansible_os_family == "Debian"
      user:
        name: vectorspace
        password: $6$vWpDsmcPtXg5QeQE$gQe0ocyTDIukYJ8NBPil8nf.qNRa10W0LRw1w5n39TiJxAnV6jpjAk23SdX907HZBwLk2AvieMcyZOUiE9DpJ/
        shell: /bin/bash
        groups: dialout
        append: yes

    - file: dest=/home/vectorspace owner=vectorspace group=vectorspace mode=u=rwX,g=rX,o=rX recurse=yes

    - name: Create Debian-exim group
      when: ansible_os_family == "Debian"
      group:
        name: Debian-exim
        state: present
