# FreeCAD development is happening at a rapid pace, well beyond what Debian is keeping up with
# and because our FRC team uses FreeCAD, it's important that we keep up to date.
# The goal is to provide two applicatio shortcuts: -stable and -dev
- name: Install latest FreeCAD
  hosts: computer-lab, office
  become: yes
  become_method: su
  ignore_errors: false
  vars:
    mime_defaults:
      application/x-extension-fcstd: freecad-latest.desktop
      model/step: freecad-latest.desktop
      model/obj: freecad-latest.desktop
      model/iges: freecad-latest.desktop


  tasks:

  # - name: FreeCAD clean build
  #   command: rm -rf /opt/freecad-source/build
  
  - name: Check if freecad executable exists
    stat:
      path: /opt/freecad-source
    register: stat_result

  - name: Check if freecad build directory exists
    stat:
      path: /opt/freecad-source/build/bin/FreeCAD
    register: build_result

# If no Freecad directory
  - name: FreeCAD clone from github
    when: not stat_result.stat.exists
    command: git clone --recurse-submodules https://github.com/FreeCAD/FreeCAD.git /opt/freecad-source
    
# if no build directory
  - name: FreeCAD pull latest
    when: not build_result.stat.exists
    command: git -C /opt/freecad-source pull --recurse-submodules 

  - name: clean untracked files
    when: not build_result.stat.exists
    command: chdir=/opt/freecad-source/ git clean -df

  - name: "make build directory"
    when: not build_result.stat.exists
    ansible.builtin.file:
      path: /opt/freecad-source/build
      state: directory

  - name: "Install FreeCAD dependencies"
    apt:
        name: ['freecad']
        state: build-dep

  - name: "Install more FreeCAD dependencies"
    apt:
        name: ['libtool',
	'lsb-release',
	'cmake',
	'build-essential',
	'libboost-dev',
	'libboost-date-time-dev',
	'libboost-filesystem-dev',
	'libboost-graph-dev',
	'libboost-iostreams-dev',
	'libboost-program-options-dev',
	'libboost-python-dev',
	'libboost-regex-dev',
	'libboost-serialization-dev',
	'libboost-thread-dev',
	'libeigen3-dev',
	'libgts-bin',
	'libgts-dev',
	'libkdtree++-dev',
	'libmedc-dev',
	'libopencv-dev',
	'libproj-dev',
	'libvtk9-dev',
	'libx11-dev',
	'libxerces-c-dev',
	'libyaml-cpp-dev',
	'libzipios++-dev',
	'libpcl-dev',
	'pybind11-dev',
	'qt6-base-dev',
	'qt6-svg-dev',
	'qt6-tools-dev',
	'qt6-webengine-dev',
	'libpyside6-dev',
	'libshiboken6-dev',
	'pyside6-tools',
	'pyqt6-dev-tools',
	'python3-dev',
	'python3-lark',
	'python3-matplotlib',
	'python3-packaging',
	'python3-pivy',
	'python3-ply',
	'python3-pyside6.qtcore',
	'python3-pyside6.qtgui',
	'python3-pyside6.qtnetwork',
	'python3-pyside6.qtsvg',
	'python3-pyside6.qtwebchannel',
	'python3-pyside6.qtwebenginecore',
	'python3-pyside6.qtwebenginequick',
	'python3-pyside6.qtwebenginewidgets',
	'python3-pyside6.qtwidgets']

  # - name: "Install Thumbnail viewer for Thunar"
  #   apt:
  #       name: ['tumbler', 'tumbler-plugins-extra']
  
  - name: "Go to build directory and cmake"
    when: not build_result.stat.exists
    command: chdir=/opt/freecad-source/build cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="-O3 -march=native -DNDEBUG" -DFREECAD_USE_PCH=ON -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF ../

  - name: "make"
    when: not build_result.stat.exists
    command: chdir=/opt/freecad-source/build make -j8

  - name: "Install FreeCAD desktop file"
    copy:
      src: ../config_files/freecad-latest.desktop
      dest: /usr/share/applications/
      owner: root

  - name: Install Techdraw Templates
    copy:
      src: ../config_files/VS_Letter_Landscape_BotRight.svg
      dest: /opt/freecad-source/build/share/Mod/TechDraw/Templates/
      owner: root

  - name: Install Techdraw Templates2
    copy:
      src: ../config_files/VS_FRC_USLetter_Landscape1_V2.svg
      dest: /opt/freecad-source/build/share/Mod/TechDraw/Templates/
      owner: root

  - name: Spacemouse support for CAD
    apt:
      name: ['spacenavd', 'libspnav-dev']
      state: latest
      force: yes

  - name: Set latest freecad as default
    command: xdg-mime default freecad-latest.desktop application/x-extension-fcstd



  - name: Ensure /etc/xdg exists
    ansible.builtin.file:
      path: /etc/xdg
      state: directory
      mode: '0755'

  - name: Configure system MIME defaults
    ansible.builtin.copy:
      dest: /etc/xdg/mimeapps.list
      owner: root
      group: root
      mode: '0644'
      content: |
        [Default Applications]
        {% for mime, app in mime_defaults.items() %}
        {{ mime }}={{ app }};
        {% endfor %}
