- name: mount_vsfs01
  hosts: clients
  become: true
  become_method: su
  tasks:
    # Needed to mount nfs volumes
    - name: Install NFS utils Debian
      when: ansible_os_family == "Debian"
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - nfs-common

    - name: Create vsfs01 directory
      file:
        path: /vsfs01
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Create vsfs01 home directory
      file:
        path: /vsfs01/home
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Create vsfs01 camera directory
      file:
        path: /vsfs01/camera
        state: directory
        owner: root
        group: members
        mode: 0755

    - name: Create vsfs01 opt directory
      file:
        path: /vsfs01/opt
        state: directory
        owner: root
        group: members
        #mode: 0755

    - name: Create vsfs01 share directory
      file:
        path: /vsfs01/share
        state: directory
        owner: root
        group: members
        mode: 0777

    - name: Create vsfs01 tv_slideshow directory
      file:
        path: /vsfs01/tv_slideshow
        state: directory
        owner: root
        group: members
        mode: 0775

    - name: Create vsfs01 packages directory
      file:
        path: /vsfs01/packages
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Mount member home space on Debian
      when: ansible_os_family == "Debian"
      mount:
        path: /vsfs01/home
        src: truenas:/mnt/vsfs01/home
        fstype: nfs
        opts: rw,async,_netdev,x-systemd.automount
        state: present

    - name: Mount shared opt
      when: ansible_os_family == "Debian"
      mount:
        path: /vsfs01/opt
        src: truenas:/mnt/vsfs01/opt
        fstype: nfs
        opts: rw,async,_netdev,x-systemd.automount
        state: present

    - name: Mount shared camera space
      when: ansible_os_family == "Debian"
      mount:
        path: /vsfs01/camera
        src: truenas:/mnt/vsfs01/camera
        fstype: nfs
        opts: rw,async,_netdev,x-systemd.automount
        state: present

    - name: Mount share space
      when: ansible_os_family == "Debian"
      mount:
        path: /vsfs01/share
        src: truenas:/mnt/vsfs01/share
        fstype: nfs
        opts: rw,async,_netdev,x-systemd.automount
        state: present

    - name: Mount tv_slideshow space
      when: ansible_os_family == "Debian"
      mount:
        path: /vsfs01/tv_slideshow
        src: truenas:/mnt/vsfs01/tv_slideshow
        fstype: nfs
        opts: rw,async,_netdev,x-systemd.automount
        state: present

    - name: Mount vsfs01 packages
      when: ansible_os_family == "Debian"
      mount:
        path: /vsfs01/packages
        src: truenas:/mnt/vsfs01/packages
        fstype: nfs
        opts: rw,async,_netdev,x-systemd.automount
        state: present
